---
language: python
python:
 - 2.7

addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck

install:
- pip install -r requirements.txt -r test-requirements.txt

script:
- make test
  # Run an update as a test
- ./update.sh
